### ISSUE TITLE
Code fails to compile on VS 2019

### ISSUE THREAD

**Issue by aymanhab** [RealTimeBiomechanics/rtosim#11]
Nice work, the code fails to compile out of the box on VS 2019 because std::bind is not found due to missing #include <functional> I can open a PR if you agree.

**Comment by cpizzolato** [comment]
Hi @aymanhab, it would be great if you could open a PR. Thanks for your help

**Comment by aymanhab** [comment]
There's already a PR with the fix at https://github.com/RealTimeBiomechanics/Concurrency/pull/1 Please merge if you agree then close this PR

**Comment by cpizzolato** [comment]
Fixed in Concurrency 7fbc48fcefded4462b9f0b315047c36653b1533e

**Comment by aymanhab** [comment]
Thanks @cpizzolato
