### ISSUE TITLE
Parametri rtosim

### ISSUE THREAD

**Issue by Gmirabile97** [RealTimeBiomechanics/rtosim#9]
Bel lavoro!
Stavo provando a fare qualche simulazione e volevo capire meglio come settare i parametri dalla cmd.
Vorrei quindi sapere che tipo di valore accettano i seguenti comandi e se hanno un minimo e massimo (se sono numeri):

--fc
 -a
  -j
--push-frequency

**Comment by cpizzolato** [comment]
English please
